### ISSUE TITLE
[identify] - No static method encodeHexString

### ISSUE THREAD

**Issue by YRodriguez** [bytedance/tiktok-business-android-sdk#23]
Hello,

I have an issue while trying to use `identify` method of the `TikTokBusinessSdk`.
I'm currently using version 1.2.6 of this library, and my `targetSdkVersion` and `compileSdkVersion` are 30.
I've set up the project following the documentation [here](https://ads.tiktok.com/marketing_api/docs?id=1701890981466113)

I got this error in console :
```
     Caused by: java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.jar)
        at org.apache.commons.codec.digest.DigestUtils.sha256Hex(DigestUtils.java:722)
        at com.tiktok.appevents.TTUserInfo.toSha256(TTUserInfo.java:41)
        at com.tiktok.appevents.TTUserInfo.setExternalId(TTUserInfo.java:55)
        at com.tiktok.appevents.TTAppEventLogger.identify(TTAppEventLogger.java:181)
        at com.tiktok.TikTokBusinessSdk.identify(TikTokBusinessSdk.java:466)
```

I tried to add `implementation 'commons-codec:commons-codec:1.15'` in my build.gradle, but it doesn't fix the problem.

It seems that there are some compatibility issues between Apache DigestUtils and Android (see [here](https://stackoverflow.com/a/9284092) - the post is old, but the problem still seems to be here).

Thank you !

**Comment by akhiljames** [comment]
@YRodriguez Thanks for reporting the issue. Looking into the issue.
